on:
  push:
    paths:
      - jupyterhub/base-cuda12.2-cudnn8-py3.9/**/*
      - .github/workflows/jupyterhub-base-cuda12.2-cudnn8-py3.9.yml
      - .github/workflows/builder.yml
    branches:
      - "master"
      - "main"
      - "latest"
  release:
    types:
      - created
jobs:
  build-jupyterhub-base-cuda122-cudnn8-py311:
    uses: ./.github/workflows/builder.yml
    with:
      context: jupyterhub/base-cuda12.2-cudnn8-py3.9
      dockerfile: jupyterhub/base-cuda12.2-cudnn8-py3.9/Dockerfile
      name: ertis-research/jupyterhub-base-cuda12.2-cudnn8-py3.9
      platforms: linux/amd64

