on:
  push:
    paths:
      - k6-influx/**/*
      - .github/workflows/k6-influx.yml
    branches:
      - "master"
      - "main"
      - "latest"
  release:
    types:
      - created
jobs:
  build-k6-influx:
    uses: ./.github/workflows/builder.yml
    with:
      context: k6-influx
      dockerfile: k6-influx/Dockerfile
      name: k6-influx
